### ISSUE TITLE
Hippogryph Bug

### ISSUE THREAD

**Issue by Pawaii** [ironrosabel/agricultural-legends#1]
Getting on Hippo is laggy but then getting off the Hippo will disconnect you from the server.
[debug-2.log.gz](https://github.com/HeyItsKairu/agricultural-legends/files/2196057/debug-2.log.gz)
[2018-07-15-1.log.gz](https://github.com/HeyItsKairu/agricultural-legends/files/2196058/2018-07-15-1.log.gz)

**Comment by ironrosabel** [comment]
Hi, a couple things to keep in mind, having a crash report (from the folder in your minecraft directory titles "crash-reports") is much more useful, as maybe next time I won't have to scroll through almost 20,000 lines of text to find the error.
This appears to be a bug with forestry beehives, not about a hippo. Forestry has issues determining the biome type, and crashes. This is not an issue with the modpack, but rather with Forestry.
You can either wait for a newer version of Forestry to fix this problem, or submit a ticket to the creators of Forestry. I highly recommend checking to see if others have had a similar problem, or if a similar ticket has been submitted already. If there is no ticket submitted, I would heavily consider submitting one yourself.
